name: fix-base-url

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "<base href=\"/\">"
          replace: "<base href=\"/mgcm_tools/\">"
          inckude: "index.html"